include: package:lints/recommended.yaml

formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
    always_use_package_imports: true
    await_only_futures: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    only_throw_errors: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    avoid_shadowing_type_parameters: true
    avoid_dynamic_calls: false
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    discarded_futures: true
    unawaited_futures: true
    empty_statements: true
    prefer_void_to_null: true
    always_put_control_body_on_new_line: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_escaping_inner_quotes: true
    parameter_assignments: true
    avoid_function_literals_in_foreach_calls: true
    avoid_returning_null_for_void: true
    avoid_setters_without_getters: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_void_async: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: true
    library_names: true
    library_prefixes: true
    library_private_types_in_public_api: true
    no_leading_underscores_for_library_prefixes: true
    omit_local_variable_types: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_contains: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_parameters: true
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_mixin: false
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true

analyzer:
  exclude:
    - lib/generated/**
    - lib/translations/**
    - lib/l10n/**
    - lib/**/*.g.dart
    - test/_data/**
    - example/**
    - examples/**
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: error
    unused_local_variable: info
    unused_element: info
    unused_field: info
    unused_import: info
    unused_shown_name: info
