coverage:
  precision: 2
  round: down
  range: "40...100"
  status:
    project:
      default:
        target: 45%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 45%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.mocks.dart"
  - "**/generated/**"
  - "**/l10n/**"
  - "test/**"
  - "example/**"
