name: engine_tracking
description: Plugin Flutter para tracking, analytics, crashlytics e logs do Engine Framework
version: 1.5.1
homepage: https://stmr.tech
repository: https://github.com/moreirawebmaster/engine-tracking
issue_tracker: https://github.com/moreirawebmaster/engine-tracking/issues
documentation: https://github.com/moreirawebmaster/engine-tracking#readme

funding:
  - https://github.com/sponsors/moreirawebmaster

topics:
  - tracking
  - analytics
  - firebase
  - crashlytics
  - logging

screenshots:
  - description: "Engine Tracking Logo"
    path: assets/images/logo.png

platforms:
  android:
  ios:

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.6.0
  faro: ^0.4.1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  clarity_flutter: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.0
  build_runner: ^2.6.0
