name: engine_tracking
description: Plugin Flutter para tracking, analytics, crashlytics e logs do Engine Framework
version: 1.0.0
homepage: https://github.com/moreirawebmasyter/engine-tracking
repository: https://github.com/moreirawebmasyter/engine-tracking

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^4.3.7
  firebase_analytics: ^11.5.0
  firebase_core: ^3.14.0
  faro: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
