name: engine_tracking
description: Plugin Flutter para tracking, analytics, crashlytics e logs do Engine Framework
version: 1.0.0
homepage: https://stmr.tech
repository: https://github.com/moreirawebmaster/engine-tracking
issue_tracker: https://github.com/moreirawebmaster/engine-tracking/issues
documentation: https://github.com/moreirawebmaster/engine-tracking#readme

funding:
  - https://github.com/sponsors/moreirawebmaster

topics:
  - tracking
  - analytics
  - firebase
  - crashlytics
  - logging

platforms:
  android:
  ios:

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^4.3.7
  firebase_analytics: ^11.5.0
  firebase_core: ^3.14.0
  faro: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
